# At the ConfigMap you can specify all static parameters you want be fixed at the initial webui start.
# For references please check:
# https://docs.openwebui.com/getting-started/env-configuration
#

apiVersion: v1
kind: ConfigMap
metadata:
  name: webui-configmap
  namespace: n8n
data:
  WEBUI_SECRET_KEY: 't0p-s3cr3t'
  OLLAMA_BASE_URL: 'http://llama-server-service.n8n.svc.cluster.local:8000'
  ENABLE_OPENAI_API: "False"
#  OPENAI_API_BASE_URL: 'http://llama-server-service.n8n.svc.cluster.local:8000'
#  ENABLE_IMAGE_GENERATION: 'True'
#  IMAGE_GENERATION_ENGINE: 'comfyui'
#  COMFYUI_BASE_URL: 'http://comfyui:8188'
#  IMAGE_STEPS: '15'
#  IMAGE_SIZE: '1024x768'
#  IMAGE_GENERATION_MODEL: 'albedobaseXL_v13.safetensors'
  CHROMA_HTTP_HOST: 'chroma'
  CHROMA_HTTP_PORT: '8000'
#  PDF_EXTRACT_IMAGES: 'True'
  DEFAULT_MODELS: 'granite4:latest'